### ISSUE TITLE
Accessing localhost results in error "Invalid API Version"

### ISSUE THREAD

**Issue by boxcee** [SemkoDev/bolero.fun#11]
When trying to access the node via `http://localhost:14265/` as specified in the Readme, I get the following message:

{"error":"Invalid API Version","duration":0}

**Comment by witwit** [comment]
Please note that the README says that it is an address that you can use for the wallet. AFAIK, you cannot simply use it in the browser, because then certain headers would need to be set first upon the request.

See here an example of an API request:
https://iota.readme.io/v1.2.0/reference

A header mus be set for: "X-IOTA-API-Version". Your browser does not do that, hence the error.
